# NOTE: Clearly don't do this in production.
PASSPHRASE=0xdeadbeef

export SIGNY_ROOT_PASSPHRASE=$PASSPHRASE
export SIGNY_TARGETS_PASSPHRASE=$PASSPHRASE
export SIGNY_SNAPSHOT_PASSPHRASE=$PASSPHRASE
export SIGNY_DELEGATION_PASSPHRASE=$PASSPHRASE